### ISSUE TITLE
Agregar numeracion de salas

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/cmyk-strawberry#109]
En la creacion de la partida, asignarle un numero a la sala en el nombre para que este se vea en la pantalla /rooms.

El campo que hay que agregar tiene que ser el `name`

**Comment by kevin-dev71** [comment]
En la DB hay un roomCounter... no se si sea buena idea tomar el valor de ahi e incrementarlo... en el notion hay una parte que explica algo sobre la numeración

**Comment by 9gustin** [comment]
puede ser 👀
