### ISSUE TITLE
Configurar hosting y deploy de la aplicación

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/cmyk-strawberry#14]
También depende de las tecnologías del readme. Hay que investigar las distintas alternativas y definir donde vamos a desplegar y ya dejarlo configurado.

Recomiendo que de ser posible se use firebase, ya que ya tenemos un proyecto ahí para la base de datos.

**Comment by kevin-dev71** [comment]
creo que lo mejor es mantenerlo todo en firebase... 🤑🤑🤑
