### ISSUE TITLE
Crear componente de reglas

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/cmyk-strawberry#17]
Este componente debe superponerse a la pagina donde se use, quizás hay que jugar con la propiedad position ahí.

Sobre el carrusel, si es complejo es posible usar una librería que lo resuelva y aplicar estilos arriba. Ejemplo: https://www.npmjs.com/package/react-responsive-carousel

Link: https://www.figma.com/file/FB4cduz9ZvdRrFHuyBVs3N/%C2%B0-Tutti-Frutti-%7C-CMYK-4.0?node-id=806%3A96

**Comment by Jseven5** [comment]
Componente de Reglas/Carousel aún sin las imágenes correspondientes. 
Falta implementación del Header debido a la ruta del homepage.
![image](https://user-images.githubusercontent.com/19292658/133499210-4cd4bd55-e2cf-4311-9b41-f23e7a587c74.png)
