### ISSUE TITLE
Implementar manejo de sesion del usuario

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/cmyk-strawberry#18]
Vamos a necesitar una identificación del usuario que esta logueado. Pero la pagina no tiene login, por lo tanto hay que encontrar la manera para generar un id único y que ese id funcione por detrás (mas allá del nombre que el usuario elige para entrar a partidas).

Es necesario acceder a este id desde distintos lugares de la aplicación.

Hay que re-pensar esto y ver como se va a solucionar 🤔

**Comment by kevin-dev71** [comment]
creo que podremos aprovechar el realtime de firebase y se manejaria un useContext de "players" y "gameRooms"

cada vez que se vaya uniendo un jugador a la sala (gameRoom) se le asigna un id con uuid, se pushea a "players" y se sincroniza a firebase....

jajaja no se si me expliqué bien o hablé de puras estupideces 🙃😛😅

**Comment by 9gustin** [comment]
Sisi me gusta la idea, porque es verdad que firebase genera uuid que nos re-serviria 😄 

Habria que sincronizar ese uuid con localStorage para que un jugador se pueda reconectar y cosas asi tambien

**Comment by kevin-dev71** [comment]
usaremos localstorage con la id generado por firebase? si es asi puedo tomar esta issue
