### ISSUE TITLE
Configurar Linter y Formatter

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/cmyk-strawberry#2]

**Comment by kevin-dev71** [comment]
a mi personalmente me gusta https://standardjs.com/, desconozco otras

**Comment by 9gustin** [comment]
Me gusta! creo que es super fácil de configurar y tiene buenas configuraciones. Acá encontré un video en donde Midudev configura eslint y despues standard. Podríamos usar standard.

https://www.youtube.com/watch?v=QpDpRmlFfqI
