### ISSUE TITLE
Investigacion sobre Firebase Realtime Database

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/cmyk-strawberry#4]
Investigar sobre el uso de  estas bases de datos en tiempo real y tomar lo necesario para luego hacer la implementación. El objetivo de esta card seria ver que métodos necesitamos para hacer que una partida ocurra en vivo y los usuarios tengan una buena experiencia en ella.

**Comment by kevin-dev71** [comment]
he estado revisando material al respecto, usaremos firebase v7, v8 o v9?

**Comment by 9gustin** [comment]
La verdad que no se, lo dejaría a criterio de cuando se haga la investigación. Habría alguna ventaja usando una versión que no sea la ultima? Sino yo usaría la ultima versión.

**Comment by kevin-dev71** [comment]
para la v8 hay varios tutoriales donde hacen app en tiempo real pero la v9 es muy reciente y el codigo es mucho mas bonito (a mi parecer) ya que es modular pero no he visto tutoriales, igual les dejo un post interesante

https://dev.to/chroline/why-the-new-firebase-web-v9-modular-sdk-is-a-game-changer-nph

**Comment by 9gustin** [comment]
mmmmmm entiendo. Lo dejamos como parte de investigación de esta card. Estaría bueno usar la v9 en caso de ser posible, y vamos siguiendo la [doc oficial de firebase](https://firebase.google.com/docs/database/web/start) y si se llega a complicar pasamos a la v8(que no es una mala opción igual)
