### ISSUE TITLE
Crear pantalla de configuracion de partida

### ISSUE THREAD

**Issue by 9gustin** [frontendcafe/cmyk-strawberry#46]
Crear el formulario de creacion de partida. Tener en cuenta las pantallas que estan arriba de la pantalla principal en el figma, estas representan que pasa cuando abris el dropdown y distintos casos.

En esta card se deberia manejar el estado del formulario para luego integrarlo con firebase, todavia no hace falta hacer la integracion, simplemente ir almacenando la informacion en un estado.

Se puede usar una libreria para manejar el formulario, como formik o react-hook-form.

Crear una ruta particular para esta vista.

Link: https://www.figma.com/file/FB4cduz9ZvdRrFHuyBVs3N/%C2%B0-Tutti-Frutti-%7C-CMYK-4.0?node-id=1953%3A29319

Prototipo: 
https://www.figma.com/proto/FB4cduz9ZvdRrFHuyBVs3N/%C2%B0-Tutti-Frutti-%7C-CMYK-4.0?node-id=1670%3A27614&scaling=scale-down&page-id=806%3A96&starting-point-node-id=1447%3A21641&show-proto-sidebar=1

**Comment by kevin-dev71** [comment]
para esta screen se necesita el componente Toogle

![image](https://user-images.githubusercontent.com/39138605/132127796-ee5b2329-1733-4578-afbd-88ffe21efbe1.png)

hay alguien trabajando en ella?

**Comment by 9gustin** [comment]
No cree una card para ese componente porque solo se usa en esta pantalla, entonces contemple que se haga en esta card :)
